CI ready
scardonau/workshop-api-testing-js pull request #3
Opened 2018-06-12 20:44 UTC by scardonau

2018-06-12 21:05 UTC, sorregom requested changes

2018-06-12 21:05 UTC, sorregom commented on .travis.yml
> +- '6'
puedes borrar esta línea, no es necesaria

2018-06-12 21:11 UTC, svillegasz approved these changes
LGTM

2018-06-13 13:23 UTC, sorregom approved these changes
LGTM

2018-06-13 13:46 UTC, merged